### ISSUE TITLE
Can not train model

### ISSUE THREAD

**Issue by Vadim2S** [PKU-YuanGroup/WF-VAE#2]
I am try train model and get error in "...\causalvideovae\model\utils\distrib_utils.py", line 24, in kl, class DiagonalGaussianDistribution
Error:  IndexError: Dimension out of range (expected to be in range of [-5, 4], but got 16)
Code: return 0.5 * torch.sum(torch.pow(self.mean, 2) + self.var - 1.0 - self.logvar, dim=list(self.mean.shape)[1:])

I am set breakpoint() and see what (for resolution 192) self.mean,shape is [1, 16, 7, 24, 24] and therefore dim=[16, 7, 24, 24].
Obviousluy this is wrong due torch.sum() "dim" parameter must be dimension indexes, not shape. For exampe Huggingface diffusers module contain class DiagonalGaussianDistribution with next code:

return 0.5 * torch.sum(torch.pow(self.mean, 2) + self.var - 1.0 - self.logvar, dim=[1, 2, 3])

**Comment by qqingzheng** [comment]
Please pull the latest commit. I've fixed the bug.

**Comment by Vadim2S** [comment]
Thanks. Checked. OK.
